### PR TITLE
Add JS1kbm

### PR DESCRIPTION
**Pull request by pvdz**
An old-school demo party in the new age. Building a JS1k demo in about 17 hours. I don't think this needs more explaining? :)

Cost: Location, food/drinks, [prizes], jury bribes
Admission fee: Whatever is needed to cover the cost, or none if the costs can be sponsored.
Location: I got nada, I could use some help with this.
People: I have _no_ idea how much interest there might be, and of course it depends on the location.
Date: Date is open for debate, but I think it'd be good to do it before cssconf, but I don't really want to do it too far before jsconf. So my preference would be the 11th.
Time: start early so we can finish before mid-night. Maybe 8am-11pm? We can announce winners right there and then, or maybe at rejectjs, or maybe at jsconf. I'm flexible.

I think it'll be super cool and fits perfectly in the jsfest idea. I have no idea how many people will turn up though. Obviously this is partially influenced by the prizes, if any. And partially by how early in the week the event will take place.

### CODE REVIEW

**Comment by rin** [comment]
Sounds really awesome, I want to join! 
That being said, can we not have it parallel to RejectJS …?

**Comment by rmehner** [comment]
I love this idea as well, but what @rin said. Having it parallel to RejectJS might be not ideal.

**Comment by zoepage** [comment]
What about the day before RejectJS? 
12th is the code retreat...

**Comment by janmonschke** [comment]
Sounds really cool!
On the 12th we'll also have the Web Audio event. But events will eventually overlap at some point ;)

**Comment by pvdz** [comment]
> But events will eventually overlap at some point ;)

Right, so this will always be the case. We could also start at 5am so we finish at 8pm and people can scurry to reject :p

**Comment by rmehner** [comment]
Only thing is, that Reject.JS is one of the bigger events on schedule, while the WebAudio-event is way smaller. Multiple smaller events work better IMHO.

Either way, I'm happy to see that being part of JSFest.berlin :)

**Comment by pvdz** [comment]
Changed my mind. Sorry.

**Pull request closed without merging**
