### PR TITLE
New Design

### PR DESCRIPTION
**Pull request by verpixelt**
The branch which is currently in use should simply be replaced with this one. It includes the new responsive design, which will be extended in the next few days.

Current state: A new designed list-view, every event has its own markdown file, we have created markdown files for all events

Future plans: we will simplify the list-view a bit (date), you get the possibility to have your own detail page for every event (logo, about text, google maps, additional info, etc.), a place or site for the about text

### CODE REVIEW

**Comment by janmonschke** [comment]
Is it ready for a merge? :)

Plus: Can you add a screenshot?

**Comment by verpixelt** [comment]
For the reason that it is a replacement with a complete different structure I wouldn't try to merge it into the existing files. 
Here's the screenshot:
jsfest berlin

**Comment by rmehner** [comment]
I've done a few Jekyll-things. I like the new layout, it's more of a schedule list and the descriptions are on the events website anyway. If everybody is cool with that, I'd go and merge this.

**Comment by verpixelt** [comment]
Go for it! ;) go go go!!!

**Comment by janmonschke** [comment]
:blush: :+1:

**Comment by Dangoo** [comment]
Thanks for merge! We're going to integrate the detail ingormation in an
upcomming release. In case there are none, the link should then direkt you
to the event page.

If you have improvement ideas, pls let us now ;)

Am Sonntag, 27. Juli 2014 schrieb Robin Mehner :

> Merged #40 https://github.com/rmehner/jsfest.berlin/pull/40.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rmehner/jsfest.berlin/pull/40#event-146027019.

## 

## 

Daniel Gooß, Development

daniel.gooss@sinnerschrader.com

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher), Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner, Nils Wollny

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | Radical Relationships

**Comment by theophani** [comment]
The design is SO NICE! :balloon: 

We should suggest to all participating events that don't themselves have brands already (such JS Conf EU, Reject.js, CSSConf.eu) to use red balloons and red signage if they can :)

**Pull request merged**
